"""RedCheck246 — Built-in wordlists for DAST path discovery.

Top 150 common sensitive paths for HTTP directory discovery.
"""

from __future__ import annotations

SENSITIVE_PATHS: list[str] = [
    # Configuration / Environment
    "/.env",
    "/.env.bak",
    "/.env.local",
    "/.env.production",
    "/.env.staging",
    "/config.php",
    "/config.yml",
    "/config.yaml",
    "/config.json",
    "/settings.py",
    "/wp-config.php",
    "/web.config",
    "/application.yml",
    "/application.properties",
    # Version control
    "/.git/config",
    "/.git/HEAD",
    "/.gitignore",
    "/.svn/entries",
    "/.hg/hgrc",
    # Admin panels
    "/admin",
    "/admin/",
    "/administrator",
    "/wp-admin",
    "/wp-login.php",
    "/phpmyadmin",
    "/phpMyAdmin",
    "/adminer.php",
    "/cpanel",
    "/manager",
    "/dashboard",
    "/login",
    "/signin",
    # API documentation
    "/api",
    "/api/",
    "/api/v1",
    "/api/v2",
    "/api/swagger.json",
    "/api/swagger.yaml",
    "/swagger.json",
    "/swagger-ui.html",
    "/openapi.json",
    "/graphql",
    "/graphiql",
    "/api-docs",
    "/redoc",
    "/docs",
    # Debug / diagnostics
    "/debug",
    "/debug/",
    "/phpinfo.php",
    "/info.php",
    "/server-info",
    "/server-status",
    "/status",
    "/health",
    "/healthcheck",
    "/actuator",
    "/actuator/health",
    "/actuator/env",
    "/actuator/configprops",
    "/trace",
    "/metrics",
    "/elmah.axd",
    # Robots / sitemap / security
    "/robots.txt",
    "/sitemap.xml",
    "/sitemap_index.xml",
    "/.well-known/security.txt",
    "/.well-known/openid-configuration",
    "/security.txt",
    "/humans.txt",
    # Backup / archive
    "/backup",
    "/backup/",
    "/backup.sql",
    "/backup.tar.gz",
    "/backup.zip",
    "/db.sql",
    "/database.sql",
    "/dump.sql",
    "/site.tar.gz",
    "/old",
    "/old/",
    "/archive",
    # Package managers / build
    "/package.json",
    "/package-lock.json",
    "/yarn.lock",
    "/composer.json",
    "/composer.lock",
    "/Gemfile",
    "/Gemfile.lock",
    "/requirements.txt",
    "/Pipfile",
    "/Pipfile.lock",
    "/pyproject.toml",
    "/pom.xml",
    "/build.gradle",
    # Cloud / infrastructure
    "/.aws/credentials",
    "/.docker/config.json",
    "/Dockerfile",
    "/docker-compose.yml",
    "/.kubernetes/",
    "/Vagrantfile",
    "/terraform.tfstate",
    "/.terraform/",
    # Sensitive files
    "/.htaccess",
    "/.htpasswd",
    "/id_rsa",
    "/id_rsa.pub",
    "/.ssh/authorized_keys",
    "/wp-content/debug.log",
    "/error.log",
    "/access.log",
    "/debug.log",
    # CMS / framework
    "/wp-content/",
    "/wp-includes/",
    "/wp-json/wp/v2/users",
    "/xmlrpc.php",
    "/readme.html",
    "/license.txt",
    "/changelog.txt",
    "/CHANGELOG.md",
    "/README.md",
    # Common application paths
    "/cgi-bin/",
    "/test",
    "/test/",
    "/testing",
    "/staging",
    "/dev",
    "/console",
    "/shell",
    "/cmd",
    "/exec",
    "/upload",
    "/uploads",
    "/uploads/",
    "/files",
    "/files/",
    "/tmp",  # noqa: S108
    "/temp",
    "/private",
    "/internal",
]
"""Top 150 common sensitive paths for HTTP endpoint discovery.

Curated from OWASP testing guides, bug-bounty playbooks, and common
web application fingerprints.
"""
